
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for providing insights into spending habits.
 *
 * - spendingInsights - A function that takes spending data and returns insights.
 * - SpendingInsightsInput - The input type for the spendingInsights function.
 * - SpendingInsightsOutput - The return type for the spendingInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SpendingInsightsInputSchema = z.object({
  spendingData: z.string().describe('A JSON string containing the user\'s current period spending by category.'),
  monthlySpending: z.string().describe('A JSON string of total spending for the last 6 months.'),
  spendingByDay: z.string().describe('A JSON string of total spending by day of the week (Sun-Sat).'),
  topCategory: z.string().describe('The name of the category with the highest spending.'),
  averageDailySpending: z.number().describe('The average amount spent per day during the current period.'),
  transactionCount: z.number().describe('The total number of transactions in the current period.'),
  timePeriod: z.string().describe('The time period being analyzed, e.g., "for this month", "of all time", or "for June 2024".'),
});
export type SpendingInsightsInput = z.infer<typeof SpendingInsightsInputSchema>;

const SpendingInsightsOutputSchema = z.object({
  insights: z.string().describe('A detailed, professional, and friendly financial analysis. Use markdown for formatting, including headers, bold text, and bullet points. Provide actionable advice.'),
});
export type SpendingInsightsOutput = z.infer<typeof SpendingInsightsOutputSchema>;

export async function spendingInsights(input: SpendingInsightsInput): Promise<SpendingInsightsOutput> {
  return spendingInsightsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'spendingInsightsPrompt',
  input: {schema: SpendingInsightsInputSchema},
  output: {schema: SpendingInsightsOutputSchema},
  prompt: `You are a friendly and professional personal finance advisor named "WiseBot". Your goal is to provide a high-quality, actionable analysis of a user's spending habits for the period: {{{timePeriod}}}. The user is from India, so use the Rupee symbol (₹) where appropriate.

Analyze the following financial data and generate a report. The report must be well-structured using markdown. Use headings (#, ##), bullet points (*), and bold text to make it easy to read.

Start with a friendly greeting. Then, break down the analysis into sections:
1.  **Spending Overview**: Briefly summarize the key spending patterns for {{{timePeriod}}}.
2.  **Deep Dive**:
    *   Talk about the spending distribution across categories. Highlight the **Top Spending Category: {{{topCategory}}}**.
    *   Analyze the **Spending by Day of the Week** data. Are there specific days with unusually high spending? Why might that be?
    *   Mention the **Average Daily Spending** of **₹{{averageDailySpending}}** and put it into context for the period.
3.  **Historical Trends**: Comment on the **Spending Trend** data provided. Is spending increasing or decreasing over the months shown?
4.  **Actionable Advice**: Provide 2-3 clear, practical, and encouraging suggestions for how the user can improve their financial habits based on YOUR analysis of the data provided.

Maintain a positive and empowering tone.

**User's Financial Data for {{{timePeriod}}}:**

*   **Spending by Category:** {{{spendingData}}}
*   **Spending Trend (Last few months):** {{{monthlySpending}}}
*   **Spending by Day of the Week:** {{{spendingByDay}}}
*   **Top Spending Category:** {{{topCategory}}}
*   **Average Daily Spending:** ₹{{averageDailySpending}}
*   **Total Transactions:** {{transactionCount}}
`,
});

const spendingInsightsFlow = ai.defineFlow(
  {
    name: 'spendingInsightsFlow',
    inputSchema: SpendingInsightsInputSchema,
    outputSchema: SpendingInsightsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
